[package]
name = "base"
version = "0.1.0"
authors = ["n-ari <fukunari.r.aa@m.titech.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.117"
serde_json = "1.0.59"
typetag = "0.1.6"
